#cloud-config
autoinstall:
  version: 1
  user-data:
    users:
      - ""
    disable_root: false
  storage:
    layout:
      name: lvm
    encrypted: true
    passphrase: "!yourpw"
    preserve_data: false
  keyboard:
    layout: "de"
  timezone: "Europe/Berlin"
  locale: "de_DE.UTF-8"
  refresh-installer:
    update: true
    channel: "latest/edge"
  packages:
    - "ubuntu-desktop"
    - "git"
    - "curl"
    - "gpg"
    - "gnome-tweaks"
    - "build-essential"
    - "wireguard"
  snaps:
    - name: "vscode"
      classic: false
    - name: "postman"
      classic: false
    - name: "vlc"
      classic: false
    - name: "keepassxc"
      classic: false
    - name: "slack"
      classic: false
    - name: "firefox"
      classic: false
  updates: "all"
  late-commands:
    - "curtin in-target --target=/target -- bash -c \"echo 'deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main' > /etc/apt/sources.list.d/microsoft-edge.list\""
    - "curtin in-target --target=/target -- wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg"
    - "curtin in-target --target=/target -- apt-get update"
    - "curtin in-target --target=/target -- apt-get install -y microsoft-edge-stable"
    - "curtin in-target --target=/target -- bash -c \"echo 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main' > /etc/apt/sources.list.d/microsoft-prod.list\""
    - "curtin in-target --target=/target -- wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft-prod.gpg"
    - "curtin in-target --target=/target -- apt-get update"
    - "curtin in-target --target=/target -- apt-get install -y intune-portal"
    - "curtin in-target --target=/target -- apt-get install -y openjdk-11-jre libicu72 libjavascriptcoregtk-4.0-18 libwebkit2gtk-4.0-37"
    - "curtin in-target --target=/target -- add-apt-repository ppa:ubuntu-enterprise-desktop/authd -y"
    - "curtin in-target --target=/target -- apt-get update"
    - "curtin in-target --target=/target -- apt-get install -y authd"
    - "curtin in-target --target=/target -- snap install authd-msentraid"
    - "curtin in-target --target=/target -- systemctl enable --now authd.service"
    - "curtin in-target --target=/target -- systemctl enable --now snap.authd-msentraid.authd-msentraid.service"
    - "curtin in-target --target=/target -- apt-get upgrade -y"
    - "curtin in-target --target=/target -- reboot"
